# Generated by Django 5.1.6 on 2025-02-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOMAIN', models.CharField(max_length=255)),
                ('QUERIES', models.JSONField()),
                ('ENTITY_TYPES', models.JSONField()),
            ],
        ),
    ]
